### ISSUE TITLE
figures in Pictures not found on line 184 of beamer manual

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/templates#1]
The following error is given when compiling the beamer manual with `pdflatex` in folder `templates/latex/beamer/themes/ulund`:
```
$ pdflatex manualulund.tex 
...
! LaTeX Error: File `titlepictureGroup' not found.
...
l.184 \end{frame}
```                 
Proposed solution: Add `Pictures/` in front of each occurrence of `titlepictureGroup`

**Comment by StefanHost** [comment]
My guess is that the issue is that the files are not installed in the local TeX-tree. The files can be found by setting 
`\graphicspath{{./Pictures/}}`

It is now included in `beamerthemeulund.sty`. Hopefully this solves the issue.

**Comment by bjornregnell** [comment]
Yes! It woks when cloning on a fresh machine with texlive and nothing else:
```
$ git clone git@github.com:lunduniversity/templates.git
$ cd templates/latex/beamer/themes/ulund/
$ pdflatex manualulund.tex
...
Output written on manualulund.pdf (20 pages, 5407454 bytes).
Transcript written on manualulund.log.
```
